required-version = "0.1.13"
target-version = "py312"
line-length = 88
indent-width = 4

[lint]
# https://docs.astral.sh/ruff/rules/
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # pep8-naming
    # "N",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # pycodestyle warnings
    "W",
    # flake8-annotations
    # "ANN",
    # flake8-bandit
    "S",
    # flake8-builtins
    "A",
    # flake8-return (RET)
    "RET",
    # pydocstyle
    # "D",
    # flake8-errmsg
    "EM",
    # flake8-slots
    "SLOT",
    # Perflint
    # "PERF",
    # flake8-unused-arguments
    # "ARG",
    # flake8-boolean-trap
    # "FBT",
]

# Ignore `E402` (import violations) in all `__init__.py` files, and in select subdirectories.
[lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs}/*" = ["E402"]

# Ignore some rules in tests
"tests/**/*.py" = [
    "S101", # asserts allowed in tests
    # "ARG", # Unused function args -> fixtures nevertheless are functionally relevant
    # "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
]
"test*.py" = ["S101"]
